### ISSUE TITLE
`decompress()` never returns

### ISSUE THREAD

**Issue by AT0myks** [vlaci/lzallright#12]
While adding support for LZO compression in [PySquashfsImage](https://github.com/matteomattei/PySquashfsImage/commit/900432e404b2245d20f54f22fe39bb277d7643ab) I tried lzallright but encountered a few problems. For a significant amount of files it will just hang forever and the only way to stop it is to kill the Python process. I also tried to use it the same way it's used in ubi_reader with `lzo.decompress(b''.join((b'\xf0', struct.pack('>I', outsize), src)))` but in that case it raises `module.LZOError: EResult.LookbehindOverrun`.

python-lzo on the other hand has no problems decompressing all that data with `lzo.decompress(src, False, outsize)`.
Maybe having the option to specify the destination buffer size like python-lzo would help?

Here are the 2 images with their list of files that cause problems if you want to replicate.
[2465.snap](https://api.snapcraft.io/api/v1/snaps/download/XKEcBqPM06H1Z7zGOdG5fbICuf8NWK5R_2465.snap)
[1862.snap](https://api.snapcraft.io/api/v1/snaps/download/XKEcBqPM06H1Z7zGOdG5fbICuf8NWK5R_1862.snap)
[files.zip](https://github.com/vlaci/lzallright/files/11526846/files.zip)

Environment: lzallright v0.1.0 / Windows x64 / Python 3.11

**Comment by vlaci** [comment]
Thanks for reporting. The fix is included in the to be released 0.2.0 version.

**Comment by AT0myks** [comment]
Can confirm that lzallright now gives the same output as python-lzo for these 2 images, with and even without size hint. Thanks for the quick fix.
