### ISSUE TITLE
Nix: function 'anonymous lambda' called with unexpected argument 'pkgsHostTarget'

### ISSUE THREAD

**Issue by qkaiser** [vlaci/lzallright#48]
The following line is causing problems in unblob: https://github.com/vlaci/lzallright/blob/e5ec79a854902eda600529c54be298b76da2d8cf/lzallright.nix#L92

```
nix flake check -L --option system x86_64-linux --extra-platforms x86_64-linux
error:
       … while checking flake output 'packages'

         at /nix/store/qsqp9xwi7c9dacxcmbac0827qrdhw04k-source/flake.nix:59:7:

           58|       ];
           59|       packages = forAllSystems (system: rec {
             |       ^
           60|         inherit (nixpkgsFor.${system}) unblob;

       … while checking the derivation 'packages.x86_64-linux.default'

         at /nix/store/qsqp9xwi7c9dacxcmbac0827qrdhw04k-source/flake.nix:61:9:

           60|         inherit (nixpkgsFor.${system}) unblob;
           61|         default = unblob;
             |         ^
           62|       });

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: function 'anonymous lambda' called with unexpected argument 'pkgsHostTarget'

       at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/pkgs/build-support/rust/hooks/default.nix:1:1:

            1| { buildPackages
             | ^
            2| , callPackage
```

<summary>Full trace</summary>
<details><pre>
nix flake check -L --option system x86_64-linux --extra-platforms x86_64-linux --show-trace
error:
       … while checking flake output 'packages'

         at /nix/store/qsqp9xwi7c9dacxcmbac0827qrdhw04k-source/flake.nix:59:7:

           58|       ];
           59|       packages = forAllSystems (system: rec {
             |       ^
           60|         inherit (nixpkgsFor.${system}) unblob;

       … while checking the derivation 'packages.x86_64-linux.default'

         at /nix/store/qsqp9xwi7c9dacxcmbac0827qrdhw04k-source/flake.nix:61:9:

           60|         inherit (nixpkgsFor.${system}) unblob;
           61|         default = unblob;
             |         ^
           62|       });

       … while evaluating the attribute 'drvPath'

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/lib/customisation.nix:268:7:

          267|     in commonAttrs // {
          268|       drvPath = assert condition; drv.drvPath;
             |       ^
          269|       outPath = assert condition; drv.outPath;

       … while evaluating the attribute 'drvPath'

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/lib/customisation.nix:268:7:

          267|     in commonAttrs // {
          268|       drvPath = assert condition; drv.drvPath;
             |       ^
          269|       outPath = assert condition; drv.outPath;

       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'python3.11-unblob-24.2.20'
         whose name attribute is located at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'propagatedBuildInputs' of derivation 'python3.11-unblob-24.2.20'

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/pkgs/stdenv/generic/make-derivation.nix:385:7:

          384|       depsHostHostPropagated      = elemAt (elemAt propagatedDependencies 1) 0;
          385|       propagatedBuildInputs       = elemAt (elemAt propagatedDependencies 1) 1;
             |       ^
          386|       depsTargetTargetPropagated  = elemAt (elemAt propagatedDependencies 2) 0;

       … while evaluating derivation 'jefferson-0.4.5'
         whose name attribute is located at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'propagatedBuildInputs' of derivation 'jefferson-0.4.5'

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/pkgs/stdenv/generic/make-derivation.nix:385:7:

          384|       depsHostHostPropagated      = elemAt (elemAt propagatedDependencies 1) 0;
          385|       propagatedBuildInputs       = elemAt (elemAt propagatedDependencies 1) 1;
             |       ^
          386|       depsTargetTargetPropagated  = elemAt (elemAt propagatedDependencies 2) 0;

       … while evaluating derivation 'python3.11-lzallright-0.2.4'
         whose name attribute is located at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'nativeBuildInputs' of derivation 'python3.11-lzallright-0.2.4'

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/pkgs/stdenv/generic/make-derivation.nix:375:7:

          374|       depsBuildBuild              = elemAt (elemAt dependencies 0) 0;
          375|       nativeBuildInputs           = elemAt (elemAt dependencies 0) 1;
             |       ^
          376|       depsBuildTarget             = elemAt (elemAt dependencies 0) 2;

       … while calling anonymous lambda

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/pkgs/stdenv/generic/make-derivation.nix:302:13:

          301|       (map (drv: getDev drv.__spliced.buildBuild or drv) (checkDependencyList "depsBuildBuild" depsBuildBuild))
          302|       (map (drv: getDev drv.__spliced.buildHost or drv) (checkDependencyList "nativeBuildInputs" nativeBuildInputs'))
             |             ^
          303|       (map (drv: getDev drv.__spliced.buildTarget or drv) (checkDependencyList "depsBuildTarget" depsBuildTarget))

       … from call site

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/pkgs/stdenv/generic/make-derivation.nix:302:18:

          301|       (map (drv: getDev drv.__spliced.buildBuild or drv) (checkDependencyList "depsBuildBuild" depsBuildBuild))
          302|       (map (drv: getDev drv.__spliced.buildHost or drv) (checkDependencyList "nativeBuildInputs" nativeBuildInputs'))
             |                  ^
          303|       (map (drv: getDev drv.__spliced.buildTarget or drv) (checkDependencyList "depsBuildTarget" depsBuildTarget))

       … while calling 'getOutput'

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/lib/attrsets.nix:1762:23:

         1761|   */
         1762|   getOutput = output: pkg:
             |                       ^
         1763|     if ! pkg ? outputSpecified || ! pkg.outputSpecified

       … while calling anonymous lambda

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/lib/lists.nix:334:29:

          333|   */
          334|   imap1 = f: list: genList (n: f (n + 1) (elemAt list n)) (length list);
             |                             ^
          335|

       … from call site

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/lib/lists.nix:334:32:

          333|   */
          334|   imap1 = f: list: genList (n: f (n + 1) (elemAt list n)) (length list);
             |                                ^
          335|

       … while calling anonymous lambda

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/pkgs/stdenv/generic/make-derivation.nix:276:15:

          275|     imap1
          276|       (index: dep:
             |               ^
          277|         if isDerivation dep || dep == null || builtins.isString dep || builtins.isPath dep then dep

       … from call site

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/pkgs/stdenv/generic/make-derivation.nix:277:12:

          276|       (index: dep:
          277|         if isDerivation dep || dep == null || builtins.isString dep || builtins.isPath dep then dep
             |            ^
          278|         else if isList dep then checkDependencyList' ([index] ++ positions) name dep

       … while calling 'isDerivation'

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/lib/attrsets.nix:1249:5:

         1248|   isDerivation =
         1249|     value: value.type or null == "derivation";
             |     ^
         1250|

       … from call site

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/lib/trivial.nix:877:7:

          876|     { # TODO: Should we add call-time "type" checking like built in?
          877|       __functor = self: f;
             |       ^
          878|       __functionArgs = args;

       … while calling anonymous lambda

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/lib/customisation.nix:104:34:

          103|       # Re-call the function but with different arguments
          104|       overrideArgs = mirrorArgs (newArgs: makeOverridable f (overrideWith newArgs));
             |                                  ^
          105|       # Change the result of the function call by applying g to it

       … from call site

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/lib/trivial.nix:877:7:

          876|     { # TODO: Should we add call-time "type" checking like built in?
          877|       __functor = self: f;
             |       ^
          878|       __functionArgs = args;

       … while calling anonymous lambda

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/lib/customisation.nix:96:17:

           95|     in
           96|     mirrorArgs (origArgs:
             |                 ^
           97|     let

       … from call site

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/lib/trivial.nix:877:7:

          876|     { # TODO: Should we add call-time "type" checking like built in?
          877|       __functor = self: f;
             |       ^
          878|       __functionArgs = args;

       … while calling anonymous lambda

         at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/lib/customisation.nix:227:65:

          226|       pkgs = f origArgs;
          227|       mkAttrOverridable = name: _: makeOverridable (mirrorArgs (newArgs: (f newArgs).${name})) origArgs;
             |                                                                 ^
          228|     in

       error: function 'anonymous lambda' called with unexpected argument 'pkgsHostTarget'

       at /nix/store/r66pr19ny80412ghfmn4wa9a8yzxj3c7-source/pkgs/build-support/rust/hooks/default.nix:1:1:

            1| { buildPackages
             | ^
            2| , callPackage
</pre>
</details>

**Comment by vlaci** [comment]
Here as well https://github.com/vlaci/lzallright/pull/46
